import type { Vector, ShapeType, NaniteGroup } from '../Types'
import type { Enemy as LegacyEnemy } from '../Types'

export interface EnemyCore {
    id: number
    type: ShapeType | 'boss'
    x: number
    y: number
    size: number
    hp: number
    maxHp: number
    spd: number
    dead: boolean
    knockback: { x: number; y: number }
}

export interface EnemyVisual {
    shape: ShapeType
    shellStage: number
    palette: string[]
    fluxState: number
    pulsePhase: number
    rotationPhase: number
    eraPalette?: string[]
    glitchPhase?: number
    crackPhase?: number
    particleOrbit?: number
    trails?: { x: number; y: number; alpha: number; rotation: number }[]
    longTrail?: { x: number; y: number }[]
    baseColor?: string
}

export interface EnemyAI {
    seen?: boolean
    spiralAngle?: number
    spiralRadius?: number
    reachedRange?: boolean
    wobblePhase?: number
    jitterX?: number
    jitterY?: number
    timer?: number
    dodgeDir?: number
    summonState?: number
    preferredMinDist?: number
    preferredMaxDist?: number
    strafeInterval?: number
}

export interface EnemyCombat {
    lastAttack: number
    lastHitTime?: number
    invincibleUntil?: number
    frozen?: number
    slowFactor?: number
    slowUntil?: number
}

export interface EnemyStatusEffects {
    isInfected?: boolean
    infectedUntil?: number
    infectionDmg?: number
    bleedTimer?: number
    bleedDmg?: number
    burnStack?: number
}

export interface EnemyElite {
    isElite: boolean
    eliteState?: number
    originalPalette?: string[]
    rarePhase?: number
    rareTimer?: number
    rareIntent?: number
    dashState?: number
    dashAngle?: number
}

export interface EnemyBoss {
    bossType: number
    bossAttackPattern: number
    bossTier?: number
    charge?: number
    berserkState?: boolean
    berserkTimer?: number
    beamState?: number
    beamTimer?: number
    beamX?: number
    beamY?: number
    beamAngle?: number
    soulLinkTargets?: number[]
    soulLinkHostId?: number
    cycloneState?: number
    cycloneTimer?: number
    shieldsInitialized?: boolean
    deflectState?: boolean
    orbitalShields?: number
    maxOrbitalShields?: number
    shieldRegenTimer?: number
    satelliteState?: number
    satelliteTimer?: number
    satelliteTargets?: { x: number; y: number }[]
    phalanxTimer?: number
    phalanxState?: number
    phalanxDrones?: string[]
    phalanxAngle?: number
    isPhalanxDrone?: boolean
    phalanxDroneAngle?: number
    crystalPositions?: Vector[]
    crystalState?: number
    nextAttackCD?: number
    rocketTimer?: number
    dementorActive?: boolean
    dementorX?: number
    dementorY?: number
    soulSuckActive?: boolean
    soulSuckTimer?: number
    soulSuckUsed?: boolean
    soulSuckCoreSize?: number
    stage?: number
    stage2StartTime?: number
    stage3StartTime?: number
    minionsSpawned?: boolean
    voidAmplified?: boolean
    voidAmpMult?: number
    untargetable?: boolean
    phase3AudioTriggered?: boolean
    isLevel3?: boolean
    isLevel4?: boolean
    isAnomaly?: boolean
    anomalyGeneration?: number
    bonusBurnPct?: number
    bonusBurnRadius?: number
    anomalyBurnTimer?: number
}

export interface EnemyWorm {
    wormId: string
    wormRole: 'head' | 'segment'
    wormSegmentIndex: number
    wormNextId?: number
    wormPrevId?: number
    wormHistory?: { x: number; y: number; state?: 'surface' | 'digging' | 'underground' | 'erupting' }[]
    wormBurrowState?: 'surface' | 'digging' | 'underground' | 'erupting'
    wormBurrowTimer?: number
    wormAIState?: 'stalking' | 'charging'
    wormFlankAngle?: number
    wormLungeTimer?: number
    wormLungeActive?: boolean
    wormOrbitDir?: number
    wormOrbitRadius?: number
    wormTrueDamage?: number
    wormPromotionTimer?: number
}

export interface EnemyLegion {
    legionId: string
    legionLeadId?: number
    legionSlot?: { x: number; y: number }
    legionShield?: number
    maxLegionShield?: number
    legionReady?: boolean
    legionCenter?: Vector
    legionJoinDelay?: number
    wasInLegion?: boolean
    hasHitThisBurst?: boolean
    isAssembling?: boolean
}

export interface Enemy extends EnemyCore {
    visual: EnemyVisual
    ai: EnemyAI
    combat: EnemyCombat
    status: EnemyStatusEffects
    elite: EnemyElite | null
    boss: EnemyBoss | null
    worm: EnemyWorm | null
    legion: EnemyLegion | null

    puddleDmgAcc?: number
    puddleDmgTimer?: number
    isRare?: boolean
    rareReal?: boolean
    canBlock?: boolean
    parentId?: number
    isExecuted?: boolean
    glitchDecoy?: boolean
    lastBlink?: number
    lastDecoy?: number
    lastLeak?: number
    forceTeleport?: boolean
    spawnedAt?: number
    spawnGracePeriod?: number
    customCollisionDmg?: number
    stunOnHit?: boolean
    xpRewardMult?: number
    soulRewardMult?: number
    mergeState?: 'none' | 'warming_up' | 'merging'
    beingConsumedBy?: number
    mergeId?: string
    mergeTimer?: number
    mergeHost?: boolean
    mergeCooldown?: number
    lockedTargetX?: number
    lockedTargetY?: number
    shieldCd?: number
    hideCd?: number
    hideTarget?: Vector | null
    hideCoverId?: number
    tacticalMode?: number
    tacticalTimer?: number
    laserTick?: number
    dodgeCooldown?: number
    lastDodge?: number
    lastBarrierTime?: number
    smokeRushEndTime?: number
    hidingStateEndTime?: number
    lastWallHit?: number
    vortexRecoveryUntil?: number
    lastVortexVelX?: number
    lastVortexVelY?: number
    vortexExitInertiaUntil?: number
    isNeutral?: boolean
    spiralDelay?: number
    isFlanker?: boolean
    flankAngle?: number
    flankDistance?: number
    flankStatus?: number
    flankTimer?: number
    minionState?: number
    orbitAngle?: number
    orbitDistance?: number
    lastLaunchTime?: number
    suicideTimer?: number
    triggeredLaunchTime?: number
    angryUntil?: number
    panicTimer?: number
    panicCooldown?: number
    trollTimer?: number
    trollRush?: boolean
    minionCount?: number
    orbitingMinionIds?: number[]
    minionIndex?: number
    isFriendly?: boolean
    attackTargetId?: number
    deathMarkExpiry?: number
    fearedUntil?: number
    stunnedUntil?: number
    temporalMonolithExplosive?: boolean
    isZombie?: boolean
    zombieState?: 'dead' | 'rising' | 'active' | 'clinging'
    zombieTimer?: number
    zombieSpd?: number
    infected?: boolean
    zombieTargetId?: number
    zombieHearts?: number
    isEnraged?: boolean
    vx?: number
    vy?: number
    distGoal?: number
    critGlitchUntil?: number
    slowPercentVal?: number
    takenDamageMultiplier?: number
    infectionAccumulator?: number
    activeNaniteCount?: number
    activeNaniteDmg?: number
    lastSpitHitId?: number
    naniteGroups?: NaniteGroup[]
    bleedAccumulator?: number
    burnTimer?: number
    isNecroticZombie?: boolean
    isGhost?: boolean
    thorns?: number
    dashTimer?: number
    dashLockX?: number
    dashLockY?: number
    thornsIgnoresArmor?: boolean
    dieOnCollision?: boolean
    lastPushX?: number
    lastPushY?: number
    parasiteLinkActive?: boolean
    parasiteTimer?: number
}

export function toNewEnemy(old: LegacyEnemy): Enemy {
    return {
        id: old.id,
        type: old.type,
        x: old.x,
        y: old.y,
        size: old.size,
        hp: old.hp,
        maxHp: old.maxHp,
        spd: old.spd,
        dead: old.dead,
        knockback: old.knockback,
        visual: {
            shape: old.shape,
            shellStage: old.shellStage,
            palette: old.palette,
            fluxState: old.fluxState,
            pulsePhase: old.pulsePhase,
            rotationPhase: old.rotationPhase,
            eraPalette: old.eraPalette,
            glitchPhase: old.glitchPhase,
            crackPhase: old.crackPhase,
            particleOrbit: old.particleOrbit,
            trails: old.trails,
            longTrail: old.longTrail,
            baseColor: old.baseColor,
        },
        ai: {
            seen: old.seen,
            spiralAngle: old.spiralAngle,
            spiralRadius: old.spiralRadius,
            reachedRange: old.reachedRange,
            wobblePhase: old.wobblePhase,
            jitterX: old.jitterX,
            jitterY: old.jitterY,
            timer: old.timer,
            dodgeDir: old.dodgeDir,
            summonState: old.summonState,
            preferredMinDist: old.preferredMinDist,
            preferredMaxDist: old.preferredMaxDist,
            strafeInterval: old.strafeInterval,
        },
        combat: {
            lastAttack: old.lastAttack,
            lastHitTime: old.lastHitTime,
            invincibleUntil: old.invincibleUntil,
            frozen: old.frozen,
            slowFactor: old.slowFactor,
            slowUntil: old.slowUntil,
        },
        status: {
            isInfected: old.isInfected,
            infectedUntil: old.infectedUntil,
            infectionDmg: old.infectionDmg,
            bleedTimer: old.bleedTimer,
            bleedDmg: old.bleedDmg,
            burnStack: old.burnStack,
        },
        elite: old.isElite ? {
            isElite: true,
            eliteState: old.eliteState,
            originalPalette: old.originalPalette,
            rarePhase: old.rarePhase,
            rareTimer: old.rareTimer,
            rareIntent: old.rareIntent,
            dashState: old.dashState,
            dashAngle: old.dashAngle,
        } : null,
        boss: old.boss ? {
            bossType: old.bossType,
            bossAttackPattern: old.bossAttackPattern,
            bossTier: old.bossTier,
            charge: old.charge,
            berserkState: old.berserkState,
            berserkTimer: old.berserkTimer,
            beamState: old.beamState,
            beamTimer: old.beamTimer,
            beamX: old.beamX,
            beamY: old.beamY,
            beamAngle: old.beamAngle,
            soulLinkTargets: old.soulLinkTargets,
            soulLinkHostId: old.soulLinkHostId,
            cycloneState: old.cycloneState,
            cycloneTimer: old.cycloneTimer,
            shieldsInitialized: old.shieldsInitialized,
            deflectState: old.deflectState,
            orbitalShields: old.orbitalShields,
            maxOrbitalShields: old.maxOrbitalShields,
            shieldRegenTimer: old.shieldRegenTimer,
            satelliteState: old.satelliteState,
            satelliteTimer: old.satelliteTimer,
            satelliteTargets: old.satelliteTargets,
            phalanxTimer: old.phalanxTimer,
            phalanxState: old.phalanxState,
            phalanxDrones: old.phalanxDrones,
            phalanxAngle: old.phalanxAngle,
            isPhalanxDrone: old.isPhalanxDrone,
            phalanxDroneAngle: old.phalanxDroneAngle,
            crystalPositions: old.crystalPositions,
            crystalState: old.crystalState,
            nextAttackCD: old.nextAttackCD,
            rocketTimer: old.rocketTimer,
            dementorActive: old.dementorActive,
            dementorX: old.dementorX,
            dementorY: old.dementorY,
            soulSuckActive: old.soulSuckActive,
            soulSuckTimer: old.soulSuckTimer,
            soulSuckUsed: old.soulSuckUsed,
            soulSuckCoreSize: old.soulSuckCoreSize,
            stage: old.stage,
            stage2StartTime: old.stage2StartTime,
            stage3StartTime: old.stage3StartTime,
            minionsSpawned: old.minionsSpawned,
            voidAmplified: old.voidAmplified,
            voidAmpMult: old.voidAmpMult,
            untargetable: old.untargetable,
            phase3AudioTriggered: old.phase3AudioTriggered,
            isLevel3: old.isLevel3,
            isLevel4: old.isLevel4,
            isAnomaly: old.isAnomaly,
            anomalyGeneration: old.anomalyGeneration,
            bonusBurnPct: old.bonusBurnPct,
            bonusBurnRadius: old.bonusBurnRadius,
            anomalyBurnTimer: old.anomalyBurnTimer,
        } : null,
        worm: old.wormId ? {
            wormId: old.wormId,
            wormRole: old.wormRole ?? 'head',
            wormSegmentIndex: old.wormSegmentIndex ?? 0,
            wormNextId: old.wormNextId,
            wormPrevId: old.wormPrevId,
            wormHistory: old.wormHistory,
            wormBurrowState: old.wormBurrowState,
            wormBurrowTimer: old.wormBurrowTimer,
            wormAIState: old.wormAIState,
            wormFlankAngle: old.wormFlankAngle,
            wormLungeTimer: old.wormLungeTimer,
            wormLungeActive: old.wormLungeActive,
            wormOrbitDir: old.wormOrbitDir,
            wormOrbitRadius: old.wormOrbitRadius,
            wormTrueDamage: old.wormTrueDamage,
            wormPromotionTimer: old.wormPromotionTimer,
        } : null,
        legion: old.legionId ? {
            legionId: old.legionId,
            legionLeadId: old.legionLeadId,
            legionSlot: old.legionSlot,
            legionShield: old.legionShield,
            maxLegionShield: old.maxLegionShield,
            legionReady: old.legionReady,
            legionCenter: old.legionCenter,
            legionJoinDelay: old.legionJoinDelay,
            wasInLegion: old.wasInLegion,
            hasHitThisBurst: old.hasHitThisBurst,
            isAssembling: old.isAssembling,
        } : null,
        puddleDmgAcc: old.puddleDmgAcc,
        puddleDmgTimer: old.puddleDmgTimer,
        isRare: old.isRare,
        rareReal: old.rareReal,
        canBlock: old.canBlock,
        parentId: old.parentId,
        isExecuted: old.isExecuted,
        glitchDecoy: old.glitchDecoy,
        lastBlink: old.lastBlink,
        lastDecoy: old.lastDecoy,
        lastLeak: old.lastLeak,
        forceTeleport: old.forceTeleport,
        spawnedAt: old.spawnedAt,
        spawnGracePeriod: old.spawnGracePeriod,
        customCollisionDmg: old.customCollisionDmg,
        stunOnHit: old.stunOnHit,
        xpRewardMult: old.xpRewardMult,
        soulRewardMult: old.soulRewardMult,
        mergeState: old.mergeState,
        beingConsumedBy: old.beingConsumedBy,
        mergeId: old.mergeId,
        mergeTimer: old.mergeTimer,
        mergeHost: old.mergeHost,
        mergeCooldown: old.mergeCooldown,
        lockedTargetX: old.lockedTargetX,
        lockedTargetY: old.lockedTargetY,
        shieldCd: old.shieldCd,
        hideCd: old.hideCd,
        hideTarget: old.hideTarget,
        hideCoverId: old.hideCoverId,
        tacticalMode: old.tacticalMode,
        tacticalTimer: old.tacticalTimer,
        laserTick: old.laserTick,
        dodgeCooldown: old.dodgeCooldown,
        lastDodge: old.lastDodge,
        lastBarrierTime: old.lastBarrierTime,
        smokeRushEndTime: old.smokeRushEndTime,
        hidingStateEndTime: old.hidingStateEndTime,
        lastWallHit: old.lastWallHit,
        vortexRecoveryUntil: old.vortexRecoveryUntil,
        lastVortexVelX: old.lastVortexVelX,
        lastVortexVelY: old.lastVortexVelY,
        vortexExitInertiaUntil: old.vortexExitInertiaUntil,
        isNeutral: old.isNeutral,
        spiralDelay: old.spiralDelay,
        isFlanker: old.isFlanker,
        flankAngle: old.flankAngle,
        flankDistance: old.flankDistance,
        flankStatus: old.flankStatus,
        flankTimer: old.flankTimer,
        minionState: old.minionState,
        orbitAngle: old.orbitAngle,
        orbitDistance: old.orbitDistance,
        lastLaunchTime: old.lastLaunchTime,
        suicideTimer: old.suicideTimer,
        triggeredLaunchTime: old.triggeredLaunchTime,
        angryUntil: old.angryUntil,
        panicTimer: old.panicTimer,
        panicCooldown: old.panicCooldown,
        trollTimer: old.trollTimer,
        trollRush: old.trollRush,
        minionCount: old.minionCount,
        orbitingMinionIds: old.orbitingMinionIds,
        minionIndex: old.minionIndex,
        isFriendly: old.isFriendly,
        attackTargetId: old.attackTargetId,
        deathMarkExpiry: old.deathMarkExpiry,
        fearedUntil: old.fearedUntil,
        stunnedUntil: old.stunnedUntil,
        temporalMonolithExplosive: old.temporalMonolithExplosive,
        isZombie: old.isZombie,
        zombieState: old.zombieState,
        zombieTimer: old.zombieTimer,
        zombieSpd: old.zombieSpd,
        infected: old.infected,
        zombieTargetId: old.zombieTargetId,
        zombieHearts: old.zombieHearts,
        isEnraged: old.isEnraged,
        vx: old.vx,
        vy: old.vy,
        distGoal: old.distGoal,
        critGlitchUntil: old.critGlitchUntil,
        slowPercentVal: old.slowPercentVal,
        takenDamageMultiplier: old.takenDamageMultiplier,
        infectionAccumulator: old.infectionAccumulator,
        activeNaniteCount: old.activeNaniteCount,
        activeNaniteDmg: old.activeNaniteDmg,
        lastSpitHitId: old.lastSpitHitId,
        naniteGroups: old.naniteGroups,
        bleedAccumulator: old.bleedAccumulator,
        burnTimer: old.burnTimer,
        isNecroticZombie: old.isNecroticZombie,
        isGhost: old.isGhost,
        thorns: old.thorns,
        dashTimer: old.dashTimer,
        dashLockX: old.dashLockX,
        dashLockY: old.dashLockY,
        thornsIgnoresArmor: old.thornsIgnoresArmor,
        dieOnCollision: old.dieOnCollision,
        lastPushX: old.lastPushX,
        lastPushY: old.lastPushY,
        parasiteLinkActive: old.parasiteLinkActive,
        parasiteTimer: old.parasiteTimer,
    }
}

export function toLegacyEnemy(newE: Enemy): LegacyEnemy {
    return {
        id: newE.id,
        type: newE.type,
        x: newE.x,
        y: newE.y,
        size: newE.size,
        hp: newE.hp,
        maxHp: newE.maxHp,
        spd: newE.spd,
        dead: newE.dead,
        knockback: newE.knockback,
        shape: newE.visual.shape,
        shellStage: newE.visual.shellStage,
        palette: newE.visual.palette,
        fluxState: newE.visual.fluxState,
        pulsePhase: newE.visual.pulsePhase,
        rotationPhase: newE.visual.rotationPhase,
        eraPalette: newE.visual.eraPalette,
        glitchPhase: newE.visual.glitchPhase,
        crackPhase: newE.visual.crackPhase,
        particleOrbit: newE.visual.particleOrbit,
        trails: newE.visual.trails,
        longTrail: newE.visual.longTrail,
        baseColor: newE.visual.baseColor,
        seen: newE.ai.seen,
        spiralAngle: newE.ai.spiralAngle,
        spiralRadius: newE.ai.spiralRadius,
        reachedRange: newE.ai.reachedRange,
        wobblePhase: newE.ai.wobblePhase,
        jitterX: newE.ai.jitterX,
        jitterY: newE.ai.jitterY,
        timer: newE.ai.timer,
        dodgeDir: newE.ai.dodgeDir,
        summonState: newE.ai.summonState,
        preferredMinDist: newE.ai.preferredMinDist,
        preferredMaxDist: newE.ai.preferredMaxDist,
        strafeInterval: newE.ai.strafeInterval,
        lastAttack: newE.combat.lastAttack,
        lastHitTime: newE.combat.lastHitTime,
        invincibleUntil: newE.combat.invincibleUntil,
        frozen: newE.combat.frozen,
        slowFactor: newE.combat.slowFactor,
        slowUntil: newE.combat.slowUntil,
        isInfected: newE.status.isInfected,
        infectedUntil: newE.status.infectedUntil,
        infectionDmg: newE.status.infectionDmg,
        bleedTimer: newE.status.bleedTimer,
        bleedDmg: newE.status.bleedDmg,
        burnStack: newE.status.burnStack,
        isElite: newE.elite?.isElite,
        eliteState: newE.elite?.eliteState,
        originalPalette: newE.elite?.originalPalette,
        rarePhase: newE.elite?.rarePhase,
        rareTimer: newE.elite?.rareTimer,
        rareIntent: newE.elite?.rareIntent,
        dashState: newE.elite?.dashState,
        dashAngle: newE.elite?.dashAngle,
        boss: newE.boss !== null,
        bossType: newE.boss?.bossType ?? 0,
        bossAttackPattern: newE.boss?.bossAttackPattern ?? 0,
        bossTier: newE.boss?.bossTier,
        charge: newE.boss?.charge,
        berserkState: newE.boss?.berserkState,
        berserkTimer: newE.boss?.berserkTimer,
        beamState: newE.boss?.beamState,
        beamTimer: newE.boss?.beamTimer,
        beamX: newE.boss?.beamX,
        beamY: newE.boss?.beamY,
        beamAngle: newE.boss?.beamAngle,
        soulLinkTargets: newE.boss?.soulLinkTargets,
        soulLinkHostId: newE.boss?.soulLinkHostId,
        cycloneState: newE.boss?.cycloneState,
        cycloneTimer: newE.boss?.cycloneTimer,
        shieldsInitialized: newE.boss?.shieldsInitialized,
        deflectState: newE.boss?.deflectState,
        orbitalShields: newE.boss?.orbitalShields,
        maxOrbitalShields: newE.boss?.maxOrbitalShields,
        shieldRegenTimer: newE.boss?.shieldRegenTimer,
        satelliteState: newE.boss?.satelliteState,
        satelliteTimer: newE.boss?.satelliteTimer,
        satelliteTargets: newE.boss?.satelliteTargets,
        phalanxTimer: newE.boss?.phalanxTimer,
        phalanxState: newE.boss?.phalanxState,
        phalanxDrones: newE.boss?.phalanxDrones,
        phalanxAngle: newE.boss?.phalanxAngle,
        isPhalanxDrone: newE.boss?.isPhalanxDrone,
        phalanxDroneAngle: newE.boss?.phalanxDroneAngle,
        crystalPositions: newE.boss?.crystalPositions,
        crystalState: newE.boss?.crystalState,
        nextAttackCD: newE.boss?.nextAttackCD,
        rocketTimer: newE.boss?.rocketTimer,
        dementorActive: newE.boss?.dementorActive,
        dementorX: newE.boss?.dementorX,
        dementorY: newE.boss?.dementorY,
        soulSuckActive: newE.boss?.soulSuckActive,
        soulSuckTimer: newE.boss?.soulSuckTimer,
        soulSuckUsed: newE.boss?.soulSuckUsed,
        soulSuckCoreSize: newE.boss?.soulSuckCoreSize,
        stage: newE.boss?.stage,
        stage2StartTime: newE.boss?.stage2StartTime,
        stage3StartTime: newE.boss?.stage3StartTime,
        minionsSpawned: newE.boss?.minionsSpawned,
        voidAmplified: newE.boss?.voidAmplified,
        voidAmpMult: newE.boss?.voidAmpMult,
        untargetable: newE.boss?.untargetable,
        phase3AudioTriggered: newE.boss?.phase3AudioTriggered,
        isLevel3: newE.boss?.isLevel3,
        isLevel4: newE.boss?.isLevel4,
        isAnomaly: newE.boss?.isAnomaly,
        anomalyGeneration: newE.boss?.anomalyGeneration,
        bonusBurnPct: newE.boss?.bonusBurnPct,
        bonusBurnRadius: newE.boss?.bonusBurnRadius,
        anomalyBurnTimer: newE.boss?.anomalyBurnTimer,
        wormId: newE.worm?.wormId,
        wormRole: newE.worm?.wormRole,
        wormSegmentIndex: newE.worm?.wormSegmentIndex,
        wormNextId: newE.worm?.wormNextId,
        wormPrevId: newE.worm?.wormPrevId,
        wormHistory: newE.worm?.wormHistory,
        wormBurrowState: newE.worm?.wormBurrowState,
        wormBurrowTimer: newE.worm?.wormBurrowTimer,
        wormAIState: newE.worm?.wormAIState,
        wormFlankAngle: newE.worm?.wormFlankAngle,
        wormLungeTimer: newE.worm?.wormLungeTimer,
        wormLungeActive: newE.worm?.wormLungeActive,
        wormOrbitDir: newE.worm?.wormOrbitDir,
        wormOrbitRadius: newE.worm?.wormOrbitRadius,
        wormTrueDamage: newE.worm?.wormTrueDamage,
        wormPromotionTimer: newE.worm?.wormPromotionTimer,
        legionId: newE.legion?.legionId,
        legionLeadId: newE.legion?.legionLeadId,
        legionSlot: newE.legion?.legionSlot,
        legionShield: newE.legion?.legionShield,
        maxLegionShield: newE.legion?.maxLegionShield,
        legionReady: newE.legion?.legionReady,
        legionCenter: newE.legion?.legionCenter,
        legionJoinDelay: newE.legion?.legionJoinDelay,
        wasInLegion: newE.legion?.wasInLegion,
        hasHitThisBurst: newE.legion?.hasHitThisBurst,
        isAssembling: newE.legion?.isAssembling,
        puddleDmgAcc: newE.puddleDmgAcc,
        puddleDmgTimer: newE.puddleDmgTimer,
        isRare: newE.isRare,
        rareReal: newE.rareReal,
        canBlock: newE.canBlock,
        parentId: newE.parentId,
        isExecuted: newE.isExecuted,
        glitchDecoy: newE.glitchDecoy,
        lastBlink: newE.lastBlink,
        lastDecoy: newE.lastDecoy,
        lastLeak: newE.lastLeak,
        forceTeleport: newE.forceTeleport,
        spawnedAt: newE.spawnedAt,
        spawnGracePeriod: newE.spawnGracePeriod,
        customCollisionDmg: newE.customCollisionDmg,
        stunOnHit: newE.stunOnHit,
        xpRewardMult: newE.xpRewardMult,
        soulRewardMult: newE.soulRewardMult,
        mergeState: newE.mergeState,
        beingConsumedBy: newE.beingConsumedBy,
        mergeId: newE.mergeId,
        mergeTimer: newE.mergeTimer,
        mergeHost: newE.mergeHost,
        mergeCooldown: newE.mergeCooldown,
        lockedTargetX: newE.lockedTargetX,
        lockedTargetY: newE.lockedTargetY,
        shieldCd: newE.shieldCd,
        hideCd: newE.hideCd,
        hideTarget: newE.hideTarget,
        hideCoverId: newE.hideCoverId,
        tacticalMode: newE.tacticalMode,
        tacticalTimer: newE.tacticalTimer,
        laserTick: newE.laserTick,
        dodgeCooldown: newE.dodgeCooldown,
        lastDodge: newE.lastDodge,
        lastBarrierTime: newE.lastBarrierTime,
        smokeRushEndTime: newE.smokeRushEndTime,
        hidingStateEndTime: newE.hidingStateEndTime,
        lastWallHit: newE.lastWallHit,
        vortexRecoveryUntil: newE.vortexRecoveryUntil,
        lastVortexVelX: newE.lastVortexVelX,
        lastVortexVelY: newE.lastVortexVelY,
        vortexExitInertiaUntil: newE.vortexExitInertiaUntil,
        isNeutral: newE.isNeutral,
        spiralDelay: newE.spiralDelay,
        isFlanker: newE.isFlanker,
        flankAngle: newE.flankAngle,
        flankDistance: newE.flankDistance,
        flankStatus: newE.flankStatus,
        flankTimer: newE.flankTimer,
        minionState: newE.minionState,
        orbitAngle: newE.orbitAngle,
        orbitDistance: newE.orbitDistance,
        lastLaunchTime: newE.lastLaunchTime,
        suicideTimer: newE.suicideTimer,
        triggeredLaunchTime: newE.triggeredLaunchTime,
        angryUntil: newE.angryUntil,
        panicTimer: newE.panicTimer,
        panicCooldown: newE.panicCooldown,
        trollTimer: newE.trollTimer,
        trollRush: newE.trollRush,
        minionCount: newE.minionCount,
        orbitingMinionIds: newE.orbitingMinionIds,
        minionIndex: newE.minionIndex,
        isFriendly: newE.isFriendly,
        attackTargetId: newE.attackTargetId,
        deathMarkExpiry: newE.deathMarkExpiry,
        fearedUntil: newE.fearedUntil,
        stunnedUntil: newE.stunnedUntil,
        temporalMonolithExplosive: newE.temporalMonolithExplosive,
        isZombie: newE.isZombie,
        zombieState: newE.zombieState,
        zombieTimer: newE.zombieTimer,
        zombieSpd: newE.zombieSpd,
        infected: newE.infected,
        zombieTargetId: newE.zombieTargetId,
        zombieHearts: newE.zombieHearts,
        isEnraged: newE.isEnraged,
        vx: newE.vx,
        vy: newE.vy,
        distGoal: newE.distGoal,
        critGlitchUntil: newE.critGlitchUntil,
        slowPercentVal: newE.slowPercentVal,
        takenDamageMultiplier: newE.takenDamageMultiplier,
        infectionAccumulator: newE.infectionAccumulator,
        activeNaniteCount: newE.activeNaniteCount,
        activeNaniteDmg: newE.activeNaniteDmg,
        lastSpitHitId: newE.lastSpitHitId,
        naniteGroups: newE.naniteGroups,
        bleedAccumulator: newE.bleedAccumulator,
        burnTimer: newE.burnTimer,
        isNecroticZombie: newE.isNecroticZombie,
        isGhost: newE.isGhost,
        thorns: newE.thorns,
        dashTimer: newE.dashTimer,
        dashLockX: newE.dashLockX,
        dashLockY: newE.dashLockY,
        thornsIgnoresArmor: newE.thornsIgnoresArmor,
        dieOnCollision: newE.dieOnCollision,
        lastPushX: newE.lastPushX,
        lastPushY: newE.lastPushY,
        parasiteLinkActive: newE.parasiteLinkActive,
        parasiteTimer: newE.parasiteTimer,
    }
}
