


export const GAME_CONFIG = {

    PLAYER: {
        HITBOX_RADIUS: 64,
        WALL_BOUNCE_SPEED: 37.5,
        WALL_DAMAGE_PERCENT: 0.10,
        ARMOR_CONSTANT: 171,
        HISTORY_LENGTH: 60,
        KNOCKBACK_DECAY: 0.85,
        SPAWN_DURATION: 2.1,
    },


    ENEMY: {
        BASE_SPAWN_RATE: 1.5,
        SPAWN_RATE_PER_MINUTE: 0.1,
        BOSS_SPAWN_INTERVAL: 120,


        SNITCH_HP: 1,
        SNITCH_SPEED_MULT: 0.7,


        MERGE_TIMER: 3.0,
        MERGE_THRESHOLD_PENTAGON: 5,
        MERGE_THRESHOLD_DEFAULT: 10,
        MERGE_HP_MULT_PENTAGON: 6,
        MERGE_HP_MULT_DEFAULT: 12,
        MERGE_XP_MULT_PENTAGON: 7,
        MERGE_XP_MULT_DEFAULT: 14,
        MERGE_SIZE_MULT: 1.55,
        MERGE_SOUL_MULT_PENTAGON: 5,
        MERGE_SOUL_MULT_DEFAULT: 10,


        MINION_DAMAGE_RATIO: 0.15,
        MINION_STUN_DAMAGE_RATIO: 0.03,



        COLLISION_POWER_SCALING: 0.6,
    },


    SKILLS: {

        WAVE_SHOTS_REQUIRED: 15,
        WAVE_RANGE: {
            LVL1: 1500,
            LVL3: 1500
        },
        WAVE_DAMAGE_MULT: {
            LVL1: 2.0,
            LVL3: 3.5
        },
        WAVE_SPEED: 45,
        WAVE_COOLDOWN: 30,
        WAVE_COOLDOWN_LVL4: 20,


        PUDDLE_COOLDOWN: 25,
        EPI_COOLDOWN: 30,
        MONOLITH_COOLDOWN: 18,
        CHRONO_DEVOURER_COOLDOWN: 15,
        KINETIC_ZAP_COOLDOWN: 5.0,
        BLACKHOLE_COOLDOWN: 10,
        COSMIC_COOLDOWN: 8,
        STORM_CIRCLE_MAX_CHARGE: 10,
        STORM_CIRCLE_RECHARGE_DELAY: 3,
        ORBITAL_VORTEX_COOLDOWN: 20,
        ORBITAL_VORTEX_DURATION: 2,
        ORBITAL_VORTEX_RECHARGE_DELAY: 1,
        ORBITAL_VORTEX_RADIUS: 800,
        ORBITAL_VORTEX_SPEED_MULT: 4.0,

        SANDBOX_COOLDOWN: 15,
        SANDBOX_DURATION: 3,
        SANDBOX_RADIUS: 176,


        CRIT_BASE_CHANCE: 0.05,
        CRIT_BASE_MULT: 2.0,
        DEATH_MARK_DURATION: Infinity,
        DEATH_MARK_COOLDOWN: 10,
        DEATH_MARK_MULT: 3.0,
        EXECUTE_BASE_CHANCE_HIT: 0.02,
        BOSS_EXECUTE_CHANCE_HIT: 0.02,
        BOSS_PERCENT_HP_ON_HIT: 0.10,


        LIFESTEAL_PERCENT: 0.03,
        MAX_HP_DMG_PERCENT: 0.02,
        OVERHEAL_SHIELD_MULT: 2.0,


        REFLECT_DAMAGE_PERCENT: 0.002,
    },


    DASH: {
        DISTANCE: 240,
        DURATION: 0.18,
        COOLDOWN: 4.0,
    },


    PROJECTILE: {
        PLAYER_BULLET_SPEED: 20,
        PLAYER_BULLET_LIFE: 140,
        PLAYER_BULLET_SIZE: 4,

        ENEMY_BULLET_SPEED: 10,
        ENEMY_BULLET_LIFE: 300,
        ENEMY_BULLET_SIZE: 6,
    }
};
