import type { LegendaryHex } from '../core/Types';

export const LEGENDARY_UPGRADES: Record<string, LegendaryHex> = {
    EcoDMG: {
        id: 'eco_dmg',
        name: 'STORM OF STEEL',
        desc: '+1 DMG per kill',
        description: 'System-integrated kinetic resonators that convert combat data into localized weapon enhancements.',
        lore: 'A forgotten prototype from the Solar Wars, the Storm of Steel harvests the kinetic energy of fallen foes to calibrate your weapon arrays for higher density impacts.',
        category: 'Economic',
        type: 'EcoDMG',
        level: 1,
        killsAtAcquisition: 0,
        customIcon: '/assets/hexes/EcoDMG.png',
        forgedAt: ['Exis']
    },
    EcoXP: {
        id: 'eco_xp',
        name: 'NEURAL HARVEST',
        desc: '+1 XP per kill',
        description: 'Bio-mechanical neural links that extract high-fidelity tactical data during enemy neutralization.',
        lore: 'The Neural Harvest protocol was designed for rapid AI training in hostile sectors, leaching every bit of processed data from destroyed units to accelerate evolution.',
        category: 'Economic',
        type: 'EcoXP',
        level: 1,
        killsAtAcquisition: 0,
        customIcon: '/assets/hexes/EcoXP.png',
        forgedAt: ['Exis']
    },
    EcoHP: {
        id: 'eco_hp',
        name: 'ESSENCE SYPHON',
        desc: '+1 Max HP per kill',
        description: 'Nano-molecular reconstructors that repurpose organic matter from fallen targets into defensive plating.',
        lore: 'Life in the void is scarce; the Essence Syphon ensures nothing is wasted, stitching the remains of your enemies directly into your hull to bolster your survival.',
        category: 'Economic',
        type: 'EcoHP',
        level: 1,
        killsAtAcquisition: 0,
        customIcon: '/assets/hexes/EcoHP.png',
        forgedAt: ['Exis']
    },
    ComLife: {
        id: 'com_life',
        name: 'CRIMSON FEAST',
        desc: '+3% Lifesteal',
        description: 'Advanced parasitic protocols that bleed energy from enemy hulls to fuel internal repair systems.',
        lore: 'The Feast is a relentless hunger. As you strike, your siphons burrow deep, carrying back the vital energy needed to keep your systems operational even under heavy fire.',
        category: 'Combat',
        type: 'ComLife',
        level: 1,
        killsAtAcquisition: 0,
        customIcon: '/assets/hexes/ComLife.png',
        forgedAt: ['Apex']
    },
    ComCrit: {
        id: 'com_crit',
        name: 'SHATTERED FATE',
        desc: '+5% Crit Chance',
        description: 'Quantum-synchronized targeting sensors that identify and exploit structural weaknesses in real-time.',
        lore: 'Fate is calculated, not random. These sensors scan for the exact micro-second of vulnerability, allowing your munitions to tear through the toughest armor like glass.',
        category: 'Combat',
        type: 'ComCrit',
        level: 1,
        killsAtAcquisition: 0,
        customIcon: '/assets/hexes/ComCrit.png',
        forgedAt: ['Apex']
    },
    ComWave: {
        id: 'com_wave',
        name: 'TERROR PULSE',
        desc: 'Active: Sonic Shockwave',
        description: 'High-frequency sonic resonators that discharge a circular wave of psychological interference and physical force.',
        lore: 'The pulse doesn\'t just break hulls; it shatters morale. The oscillating waves resonate at frequencies that disrupt neural patterns, leaving enemies paralyzed with fear.',
        category: 'Combat',
        type: 'ComWave',
        level: 1,
        killsAtAcquisition: 0,
        customIcon: '/assets/hexes/ComWave.png',
        forgedAt: ['Apex']
    },
    DefPuddle: {
        id: 'def_puddle',
        name: 'TOXIC SWAMP',
        desc: 'Active: Spawn Toxic Puddle',
        description: 'Chemical dispersal system that saturates the region with corrosive, neuro-inhibiting compounds.',
        lore: 'The Toxic Swamp creates a localized dead-zone. Corrosive compounds melt through enemy shielding while neuro-toxins slow their movement to a crawl.',
        category: 'Defensive',
        type: 'DefPuddle',
        level: 1,
        killsAtAcquisition: 0,
        customIcon: '/assets/hexes/DefPuddle.png',
        forgedAt: ['Bastion']
    },
    DefEpi: {
        id: 'def_epi',
        name: 'EPICENTER',
        desc: 'Active: Channel Spikes',
        description: 'Gravimetric stabilization unit that channels tectonic energy into localized crystalline spikes.',
        lore: 'Become the center of gravity. As the spikes emerge, the sheer force of the energy channel locks you in place but creates a sanctuary of total destruction around you.',
        category: 'Defensive',
        type: 'DefEpi',
        level: 1,
        killsAtAcquisition: 0,
        customIcon: '/assets/hexes/DefEpi.png',
        forgedAt: ['Bastion']
    },
    EcoShield: {
        id: 'eco_shield',
        name: 'AEGIS PROTOCOL',
        desc: 'Adaptive Resistance Scaling',
        description: 'Adaptive plating algorithms that strengthen structural integrity based on combat data.',
        lore: 'The Aegis is a living shield. It learns from every hit taken and every enemy destroyed, reinforcing your chassis until it becomes an impenetrable fortress.',
        category: 'Economic',
        type: 'EcoShield',
        level: 1,
        killsAtAcquisition: 0,
        customIcon: '/assets/hexes/EcoShield.png',
        forgedAt: ['Exis']
    },
    DefBattery: {
        id: 'kin_bat',
        name: 'KINETIC BATTERY',
        desc: 'Converts Armor to Shockwaves',
        description: 'Experimental capacitor bank that stores kinetic impact energy and releases it as devastating shockwaves.',
        lore: 'Why simply deflect a blow when you can catch it, amplify it, and send it back tenfold? The Kinetic Battery turns your defense into the ultimate offense.',
        category: 'Defensive',
        type: 'DefBattery',
        level: 1,
        killsAtAcquisition: 0,
        customIcon: '/assets/hexes/DefBattery.png',
        forgedAt: ['Bastion']
    },
    ComRadiation: {
        id: 'rad_core',
        name: 'RADIATION CORE',
        desc: 'Global Decay Aura',
        description: 'Unstable isotope reactor that emits a lethal 500px radiation aura. Damage intensity scales with proximity; the closer an enemy is to your core, the faster they decay.',
        lore: 'Harvested from a dying star, this core pulses with entropy. To stand near you is to age a thousand years in a second.',
        category: 'Combat',
        type: 'ComRadiation',
        level: 1,
        killsAtAcquisition: 0,
        customIcon: '/assets/hexes/ComRadiation.png',
        forgedAt: ['Apex']
    },
    DefPlatting: {
        id: 'chrono_plate',
        name: 'CHRONO PLATING',
        desc: 'Time-Scaling Defense',
        description: 'Temporal alloy plating that hardening over time, becoming virtually indestructible the longer you survive.',
        lore: 'Forged outside of time, this armor doesn\'t just resist damage; it denies the very event of impact, rewriting history to keep you intact.',
        category: 'Defensive',
        type: 'DefPlatting',
        level: 1,
        killsAtAcquisition: 0,
        customIcon: '/assets/hexes/DefPlatting.png',
        forgedAt: ['Bastion']
    },
    XenoAlchemist: {
        id: 'xeno_alchemist',
        name: 'THE XENO-ALCHEMIST',
        desc: 'Economic / Defensive Fusion',
        description: 'A volatile fusion of Neural Harvest and Toxic Swamp. Converts your defensive acid puddles into high-yield resource refineries.',
        lore: 'When the greed of the Neural Harvest met the toxicity of the Swamp, the Xeno-Alchemist was born. It doesn\'t just kill; it extracts every possible resource from the dissolving remains of its victims.',
        category: 'Fusion',
        categories: ['Economic', 'Defensive'],
        type: 'XenoAlchemist',
        level: 5,
        killsAtAcquisition: 0,
        customIcon: '/assets/Fusions/THE XENO-ALCHEMIST.png'
    },
    IrradiatedMire: {
        id: 'irradiated_mire',
        name: 'THE IRRADIATED MIRE',
        desc: 'Combat / Defensive Fusion',
        description: 'A volatile fusion of Toxic Swamp and Radiation Core. Saturates the region with lethal isotopes and corrosive acids.',
        lore: 'The mire does not just dissolve flesh; it breaks down the very atoms of anything caught within its neon glow. A beautiful, glowing death sentence.',
        category: 'Fusion',
        categories: ['Combat', 'Defensive'],
        type: 'IrradiatedMire',
        level: 5,
        killsAtAcquisition: 0,
        customIcon: '/assets/Fusions/THE IRRADIATED MIRE.png'
    },
    NeuralSingularity: {
        id: 'neural_singularity',
        name: 'THE NEURAL SINGULARITY',
        desc: 'Economic / Combat Fusion',
        description: 'A mind-bending fusion of Neural Harvest and Terror Pulse. The pulse now ripples with psychic feedback, extending fear based on your enlightenment.',
        lore: 'The Singularity is not just a wave; it is a shared revelation. For a brief moment, the enemies feel the crushing weight of every experience you have ever gained. They do not just flee; they are paralyzed by the truth.',
        category: 'Fusion',
        categories: ['Economic', 'Combat'],
        type: 'NeuralSingularity',
        level: 5,
        killsAtAcquisition: 0,
        customIcon: '/assets/Fusions/THE NEURAL SINGULARITY.png'
    },
    KineticTsunami: {
        id: 'kinetic_tsunami',
        name: 'THE KINETIC TSUNAMI',
        desc: 'Economic / Combat Fusion',
        description: 'A devastating fusion of Storm of Steel and Terror Pulse. Sonic avalanches harvest kinetic trauma to amplify your power.',
        lore: 'The shockwaves are no longer just fear; they are physical trauma. It harvests the kinetic energy of everything it shatters, fueling an endless storm of destruction.',
        category: 'Fusion',
        categories: ['Economic', 'Combat'],
        type: 'KineticTsunami',
        level: 5,
        killsAtAcquisition: 0,
        customIcon: '/assets/Fusions/THE KINETIC TSUNAMI.png'
    },
    SoulShatterCore: {
        id: 'soul_shatter_core',
        name: 'THE SOUL-SHATTER CORE',
        desc: 'Combat / Economic Fusion',
        description: 'A critical fusion of Shattered Fate and Storm of Steel. Extends critical lethality through soul harvesting.',
        lore: 'The core doesn’t just record death; it shatters the very concept of survival. By feeding on the souls of the executed, it recalibrates your weapon’s frequency to absolute zero precision.',
        category: 'Fusion',
        categories: ['Combat', 'Economic'],
        type: 'SoulShatterCore',
        level: 5,
        killsAtAcquisition: 0,
        customIcon: '/assets/Fusions/THE SOUL-SHATTER CORE.png'
    },
    BloodForgedCapacitor: {
        id: 'blood_forged_capacitor',
        name: 'THE NECRO-KINETIC ENGINE',
        desc: 'Combat / Defensive Fusion',
        description: 'Kinetic shockwaves trigger lifesteal from damage dealt. Each time a zombie consumes an enemy, there is a chance to cast a green kinetic bolt.',
        lore: 'The capacitor doesn’t just store energy; it refines it through the lens of pain. Every shockwave sent through the enemy ranks carries a parasitic pulse, tearing life from their hulls and feeding it directly into your core.',
        category: 'Fusion',
        categories: ['Combat', 'Defensive'],
        type: 'BloodForgedCapacitor',
        level: 5,
        killsAtAcquisition: 0,
        customIcon: '/assets/Fusions/THE NECRO-KINETIC ENGINE.png'
    },
    GravityAnchor: {
        id: 'gravity_anchor',
        name: 'THE GRAVITY ANCHOR',
        desc: 'Defensive / Defensive Fusion',
        description: 'A structural collapse between Aegis Protocol and Epicenter. Deploys an anchor dealing damage scaling with 2% Armor and executing enemies below 5% HP.',
        lore: 'The shield is no longer just a barrier; it is a weight. It condenses the gravitational pull of your impact, anchoring it to your armor until the pressure shatters the very ground beneath you.',
        category: 'Fusion',
        categories: ['Defensive', 'Defensive'],
        type: 'GravityAnchor',
        level: 5,
        killsAtAcquisition: 0,
        customIcon: '/assets/Fusions/THE GRAVITY ANCHOR.png'
    },
    TemporalMonolith: {
        id: 'temporal_monolith',
        name: 'THE TEMPORAL MONOLITH',
        desc: 'Defensive / Defensive Fusion',
        description: 'Taking any damage increases your Cooldown Recovery Speed by 20% for 1 sec. Active: Freezes enemies in 400px for 4s. Frozen enemies explode on death for 25% MAX HP.',
        lore: 'A timeless monolith forged from raw endurance. It does not just absorb blows; it converts their kinetic energy into localized temporal accelerations, letting you move faster as the world slows down.',
        category: 'Fusion',
        categories: ['Defensive', 'Defensive'],
        type: 'TemporalMonolith',
        level: 5,
        killsAtAcquisition: 0,
        customIcon: '/assets/Fusions/THE TEMPORAL MONOLITH.png'
    },
    NeutronStar: {
        id: 'neutron_star',
        name: 'THE NEUTRON STAR',
        desc: 'EcoHP / Combat Fusion',
        description: 'A stellar collapse between Essence Syphon and Radiation Core. [EVENT HORIZON] Radiation damage increased by 2% for every 100 Max HP. 0.01% Aura DMG increase for kills by your Radiant Aura and double souls for Essence Syphon.',
        lore: 'A collapsed star’s core, bound by biological essence. It pulls everything into its inescapable reach, converting matter into pure gravitational force.',
        category: 'Fusion',
        categories: ['Economic', 'Combat'],
        type: 'NeutronStar',
        level: 5,
        killsAtAcquisition: 0,
        customIcon: '/assets/Fusions/THE NEUTRON STAR.png'
    },
    GravitationalHarvest: {
        id: 'gravitational_harvest',
        name: 'THE GRAVITATIONAL HARVEST',
        desc: 'EcoHP / Defensive Fusion',
        description: 'A stellar resonance between Essence Syphon and Epicenter. Kills within the well extend its duration. 10% of damage taken is reflected to trapped enemies.',
        lore: 'The harvest is eternal. As you pull them into your reach, their very life force is used to stabilize the gravity well, while their strikes only fuel the crushing pressure of the singularity.',
        category: 'Fusion',
        categories: ['Economic', 'Defensive'],
        type: 'GravitationalHarvest',
        level: 5,
        killsAtAcquisition: 0,
        customIcon: '/assets/Fusions/THE GRAVITATIONAL HARVEST.png'
    },
    ShatteredCapacitor: {
        id: 'shattered_capacitor',
        name: 'THE SHATTERED CAPACITOR',
        desc: '20% of damage dealt arcs as Kinetic Bolt damage to 2 nearby enemies on hit. Applies 15% of Armor as bleed for 3 seconds.',
        description: '20% of damage dealt arcs as Kinetic Bolt damage to 2 nearby enemies on hit. Applies 15% of Armor as bleed for 3 seconds.',
        lore: 'The capacitor doesn’t just store energy; it refines it through the lens of critical impact. Every arc sent through the enemy ranks identifies a structural failure, letting the next strike tear them apart.',
        category: 'Fusion',
        categories: ['Combat', 'Defensive'],
        type: 'ShatteredCapacitor',
        level: 5,
        killsAtAcquisition: 0,
        customIcon: '/assets/Fusions/THE SHATTERED CAPACITOR.png'
    },
    ChronoDevourer: {
        id: 'chrono_devourer',
        name: 'THE CHRONO-DEVOURER',
        desc: 'Combat / Defensive Fusion',
        description: 'Zombies have a 10% chance to consume enemies on first bite. Zombie kills reduce all active skill cooldowns by 0.03s.',
        lore: 'A parasitic anomaly that feeds on both temporal energy and biomatter. It trades your shields for raw devastation, while accelerating your systems with every successful consumption.',
        category: 'Fusion',
        categories: ['Combat', 'Defensive'],
        type: 'ChronoDevourer',
        level: 5,
        killsAtAcquisition: 0,
        customIcon: '/assets/Fusions/THE CHRONO-DEVOURER.png'
    },
};
